spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///ticket
      username:
      password:
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.scau.ticket.application.vo
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    use-generated-keys: true
