#ENC(...)代表已经加密后的字符串
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://1.15.255.173:3306/ticket?serverTimezone=UTC&useSSL=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: Ticket123?
  mvc:
    view:
      prefix: /
      suffix: .html
  security:
    release-path: [/index,/register,/verifycode,/existUsername,/getCode,/toLogin,/toError,/test,/testUpload]
  cache:
    cache-names: cache
    type: redis
  redis:
    host: ENC(yeFiySbSCt0800oYIy0TzzCLGesf+lbCJIDf4FIYaQJZZyhFq8biwvBU/qahi7DLUgeHw5cKh08=)
    port: 6379
    password: ENC(AVICKI0eW6JlZ+04W0Yxf4wF4+zNJOi0)
  redisson:
    address: ENC(0zoiyvk5L7ZblC9Vow99jD8ThT00N4hdeHYnPN7qqlmkVZMTWac3eQfu2yxJDHbNbYUvVDsfjUC32ZYOaj3Z0lv3uD70AisY)
    password: ENC(AVICKI0eW6JlZ+04W0Yxf4wF4+zNJOi0)

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.scau.ticket.application.*
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    use-generated-keys: true

token:
  header: bear
  secret: ticket...
  expireTime: 30
  issuer: ticket-application

fdfs:
  #读取时间
  so-timeout: 1500
  #连接超时时间
  connect-timeout: 600
  #tracker
  tracker-list: ENC(9MKyelkZFHLbi3SzgLhlaC9s6ifJygwoXxgSYET/mvw=)
  pool:
    max-total: 200
    max-total-per-key: 50

jasypt:
  encryptor:
    password: mego
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

bloomFilter:
  username:
    expectedInsertions: 100000
    falseProbability: 0.005