spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: 
      username: 
      password: 
  mvc:
    view:
      prefix: /
      suffix: .html
  security:
    release-path: [/index,/register,/verifycode,/existUsername,/getCode,/toLogin,/toError,/test,/testUpload,/alipay,/alipay/notify,/alipay/return]
  cache:
    cache-names: cache
    type: redis
  redis:
    host: 
    port: 6379
    password: 
  redisson:
    address: 
    password: 

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.scau.ticket.application.*
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    use-generated-keys: true
    auto-mapping-behavior: partial

token:
  header: bear
  secret: ticket...
  expireTime: 300
  issuer: ticket-application

fdfs:
  #读取时间
  so-timeout: 1500
  #连接超时时间
  connect-timeout: 600
  #tracker
  tracker-list: 
  pool:
    max-total: 200
    max-total-per-key: 50
  headUrl: 
  defaultImg: group1/M00/00/00/eQXtRWCXOLuAXoD5AAAMz79eafk023.jpg

jasypt:
  encryptor:
    password: 
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

bloomFilter:
  username:
    expectedInsertions: 100000
    falseProbability: 0.005

alipay:
  app_id: ENC(ZApuJvA87HJvEl2j/N3/z61yv5BGX9UBaTD+BBo2eug=)
  private_key:
  public_key: 
  return_url: http://xxx/alipay/return
  notify_url: http://xxx/alipay/notify
  format: JSON
  sign_type: RSA2
  charset: utf-8
  gateway_url: https://openapi.alipaydev.com/gateway.do
  log_path: 
logging:
  level:
    cn:
      edu:
        scau:
          ticket:
            application:
              mapper: debug
